# Publish PyPI and NPM artifacts
name: Publish
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build dist
        run: |
          pip install jupyter_packaging wheel jupyterlab~=3.0
          python setup.py sdist bdist_wheel

      - name: Javascript package
        run: |
          mkdir jsdist
          cd jupyterlab-server-proxy
          jlpm pack --filename ../jsdist/jupyterlab-server-proxy-jlpmpack.tgz

      - name: Upload Python artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          if-no-files-found: error

      - name: Upload Javascript artifact
        uses: actions/upload-artifact@v2
        with:
          name: jsdist
          path: jsdist
          if-no-files-found: error

  # https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
  publish-pypi:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Download artifacts from build
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.3.0
        with:
          password: ${{ secrets.PYPI_PASSWORD }}

  # https://docs.github.com/en/actions/language-and-framework-guides/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
  publish-npm:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      # actions/setup-node creates an .npmrc file that references NODE_AUTH_TOKEN
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org
      - name: Download artifacts from build
        uses: actions/download-artifact@v2
        with:
          name: jsdist
          path: jsdist
      - run: npm publish --dry-run ./jsdist/jupyterlab-server-proxy-jlpmpack.tgz
      - run: npm publish ./jsdist/jupyterlab-server-proxy-jlpmpack.tgz
        if: startsWith(github.ref, 'refs/tags')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
